### ISSUE TITLE
Comments on symbolic automata write up

### ISSUE THREAD

**Issue by matthewhague** [zhilin02/slreplace#12]
Minor points:
- What is an S-term?
- What is D \models \phi(x)?
- What is an S-formula and how can you substitute a term into it?
- What is the size of a formula?
- SLS formula notation out of date

**Comment by chentaolue** [comment]
Zhilin asked me to proof read the symbolic part. I included some comments there, and for me, the status is:

What is an S-term? -- this is hidden in the familiarity of many-sorted FOL ;-)
What is D \models \phi(x)? --resolved
What is an S-formula and how can you substitute a term into it? -- same as S-terms ?
What is the size of a formula? -- be defined
SLS formula notation out of date -- yes, to be aligned to sect. 4

**Comment by matthewhague** [comment]
Hmm, i thought i was familiar with FOL, but don't actually know the difference between an S-term and an S-formula...

**Comment by chentaolue** [comment]
i am not an expert, but i think for instance f(x,g(y)) is a term, but not a formula, but R(x,f(y)) would be a formula? Here, f, g are function symbols, and R is a predicate (relation) symbol. Correct me if i am wrong.

**Comment by matthewhague** [comment]
Aha.  f(x,g(y)) is still a formula (an atomic one).  As soon as you have conjunction/disjunction/&c then you have a formula but not a term.

http://mathworld.wolfram.com/First-OrderLogic.html

**Comment by chentaolue** [comment]
it is not important, just for fun, wiki thinks slightly differently

https://en.wikipedia.org/wiki/First-order_logic

Terms
The set of terms is inductively defined by the following rules:

Variables. Any variable is a term.

Functions. Any expression f(t1,...,tn) of n arguments (where each argument ti is a term and f is a function symbol of valence n) is a term. In particular, symbols denoting individual constants are nullary function symbols, and are thus terms.
Only expressions which can be obtained by finitely many applications of rules 1 and 2 are terms. For example, no expression involving a predicate symbol is a term.

Formulas 
The set of formulas (also called well-formed formulas[9] or WFFs) is inductively defined by the following rules:

Predicate symbols. If P is an n-ary predicate symbol and t1, ..., tn are terms then P(t1,...,tn) is a formula.
Equality. If the equality symbol is considered part of logic, and t1 and t2 are terms, then t1 = t2 is a formula.
Negation. If φ is a formula, then {\displaystyle \lnot } \lnot φ is a formula.
Binary connectives. If φ and ψ are formulas, then (φ {\displaystyle \rightarrow } \rightarrow  ψ) is a formula. Similar rules apply to other binary logical connectives.
Quantifiers. If {\displaystyle \varphi } \varphi  is a formula and x is a variable, then {\displaystyle \forall x\varphi } \forall x\varphi  (for all x, {\displaystyle \varphi } \varphi  holds) and {\displaystyle \exists x\varphi } \exists x\varphi  (there exists x such that {\displaystyle \varphi } \varphi ) are formulas.
Only expressions which can be obtained by finitely many applications of rules 1–5 are formulas. 

The formulas obtained from the first two rules are said to be atomic formulas.

**Comment by matthewhague** [comment]
Oh, yeah, i see.  That types at least!  Thanks.
